title: Matt Palmer
author:
  name: Matt Palmer
  email: hello@mattpalmer.io
  location: Asheville, North Carolina â›°
  location_link: https://www.exploreasheville.com/
  company: Underline Infrastructure ðŸ¢
  company_link: https://www.underline.com/
  team: Data
  job: data engineer
description: > # this means to ignore newlines until "show_excerpts:"
  Data Enginner at Underline & Swarthmore College grad. You can find me at the gym, 
  climbing rocks, or on a trail when not at work.
google_analytics: G-EC2ZQ7Y8TD
baseurl: "/"

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  skin: dark
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: mattppal
    github: mattppal
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: mattppal
    linkedin: matt-palmer
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    keybase: mattpal

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
# header_pages:
#   - about.path
#   - resume.path

# Build settings
theme: minima

plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  pages:
    output: true
